const REPO_SOURCE = {
    repos: [
        { name: "custom-jena-fuseki" },
        { name: "custom-jupyter-labs" },
        { name: "custom-maven-with-node-builder" },
        { name: "data-exploration" },
        { name: "datahub" },
        { name: "data-product-cli" },
        { name: "data-product-cli-companion" },
        { name: "data-product-management" },
        { name: "data-product-monitor" },
        { name: "data-product-operators" },
        { name: "data-product-registration-operators" },
        { name: "data-product-template" },
        { name: "data-product-watcher" },
        { name: "development-environment" },
        { name: "keycloak" },
        { name: "keycloak-config" },
        { name: "mvn-lib-analytical-data" },
        { name: "mvn-lib-bitbucket-client" },
        { name: "mvn-lib-datahub-client" },
        { name: "mvn-lib-dataproduct-vocabulary" },
        { name: "mvn-lib-jena-security" },
        { name: "mvn-lib-testing-util" }
    ],
    subDirs: [
        {
            name: "k8s",
            repos: [
                { name: "k8s-ddt-aws-efs-csi-driver" },
                { name: "k8s-ddt-aws-loadbalancer-controller" },
                { name: "k8s-ddt-calico" },
                { name: "k8s-ddt-clickhouse" },
                { name: "k8s-ddt-clickhouse-zookeeper" },
                { name: "k8s-ddt-cluster-autoscaler-autodiscover" },
                { name: "k8s-ddt-cni-metrics-helper" },
                { name: "k8s-ddt-custom-jena-fuseki" },
                { name: "k8s-ddt-datahub" },
                { name: "k8s-ddt-datahub-elasticsearch" },
                { name: "k8s-ddt-datahub-kafka" },
                { name: "k8s-ddt-datahub-schema-registry" },
                { name: "k8s-ddt-datahub-zookeeper" },
                { name: "k8s-ddt-data-product-cli-companion" },
                { name: "k8s-ddt-data-product-management" },
                { name: "k8s-ddt-data-product-monitor" },
                { name: "k8s-ddt-data-product-operators" },
                { name: "k8s-ddt-data-product-registration-operators" },
                { name: "k8s-ddt-data-product-watcher" },
                { name: "k8s-ddt-external-dns" },
                { name: "k8s-ddt-external-snapshotter" },
                { name: "k8s-ddt-flux" },
                { name: "k8s-ddt-grafana" },
                { name: "k8s-ddt-istio" },
                { name: "k8s-ddt-jaeger" },
                { name: "k8s-ddt-jupyterhub" },
                { name: "k8s-ddt-keycloak" },
                { name: "k8s-ddt-kiali" },
                { name: "k8s-ddt-knative-eventing" },
                { name: "k8s-ddt-knative-eventing-kafka" },
                { name: "k8s-ddt-knative-eventing-zookeeper" },
                { name: "k8s-ddt-logging-elasticsearch" },
                { name: "k8s-ddt-logging-fluentd" },
                { name: "k8s-ddt-logging-kibana" },
                { name: "k8s-ddt-mail-external" },
                { name: "k8s-ddt-mail-internal" },
                { name: "k8s-ddt-monitoring" },
                { name: "k8s-ddt-network-policies" },
                { name: "k8s-ddt-prometheus" },
                { name: "k8s-ddt-prometheus-stack" },
                { name: "k8s-ddt-rbac" },
                { name: "k8s-ddt-sealed-secrets" },
                { name: "k8s-ddt-tools-aws-efs-csi-driver" },
                { name: "k8s-ddt-tools-calico" },
                { name: "k8s-ddt-tools-cluster-autoscaler-autodiscover" },
                { name: "k8s-ddt-tools-cni-metrics-helper" },
                { name: "k8s-ddt-tools-external-dns" },
                { name: "k8s-ddt-tools-external-snapshotter" },
                { name: "k8s-ddt-tools-flux" },
                { name: "k8s-ddt-tools-grafana" },
                { name: "k8s-ddt-tools-harbor-core" },
                { name: "k8s-ddt-tools-harbor-jobservice" },
                { name: "k8s-ddt-tools-harbor-notary" },
                { name: "k8s-ddt-tools-harbor-portal" },
                { name: "k8s-ddt-tools-harbor-registry" },
                { name: "k8s-ddt-tools-harbor-trivy" },
                { name: "k8s-ddt-tools-ingress-controller" },
                { name: "k8s-ddt-tools-jenkins" },
                { name: "k8s-ddt-tools-kube-state-metrics" },
                { name: "k8s-ddt-tools-logging-elasticsearch" },
                { name: "k8s-ddt-tools-logging-fluentd" },
                { name: "k8s-ddt-tools-logging-kibana" },
                { name: "k8s-ddt-tools-mail-external" },
                { name: "k8s-ddt-tools-mail-internal" },
                { name: "k8s-ddt-tools-monitoring-grafana" },
                { name: "k8s-ddt-tools-monitoring-prometheus" },
                { name: "k8s-ddt-tools-monitoring-prometheus-node-exporter" },
                { name: "k8s-ddt-tools-network-policies" },
                { name: "k8s-ddt-tools-nexus" },
                { name: "k8s-ddt-tools-prometheus-stack" },
                { name: "k8s-ddt-tools-rbac" },
                { name: "k8s-ddt-tools-sealed-secrets" },
                { name: "k8s-ddt-tools-sonarqube" },
                { name: "k8s-ddt-tools-tekton-dashboard" },
                { name: "k8s-ddt-tools-tekton-pipelines" },
                { name: "k8s-ddt-tools-tekton-triggers" },
                { name: "k8s-ddt-tools-workstation-scripts" },
                { name: "k8s-ddt-workstation-scripts" },
                { name: "terraform-ddt" },
                { name: "terraform-ddt-aws-config-module" },
                { name: "terraform-ddt-common" },
                { name: "terraform-ddt-tools" },
                { name: "terraform-ddt-tools-harbor" },
                { name: "terraform-ddt-tools-nexus" }
            ]
        },
        {
            name: "dp",
            repos: [
                { name: "alle-activiteiten-ca17fee8e9c1fc31" },
                { name: "alle-activiteiten-ca17fee8e9c1fc31-shadow" },
                { name: "alle-activiteit-infrastructuren-266185d3a962c788" },
                { name: "alle-activiteit-infrastructuren-266185d3a962c788-shadow" },
                { name: "broninformatie-cji-266185d3a962c788" },
                { name: "broninformatie-cji-266185d3a962c788-shadow" },
                { name: "consolidatie-cji-266185d3a962c788" },
                { name: "consolidatie-cji-266185d3a962c788-shadow" },
                { name: "dcjm-metadata-e9e231f93c7b9817" },
                { name: "dcjm-metadata-e9e231f93c7b9817-shadow" },
                { name: "deploy-test-3db4ad1abbb8200b" },
                { name: "deploy-test-3db4ad1abbb8200b-shadow" },
                { name: "erfgoedkaart-infrastructuur-266185d3a962c788" },
                { name: "erfgoedkaart-infrastructuur-266185d3a962c788-shadow" },
                { name: "inventaris-cji-266185d3a962c788" },
                { name: "inventaris-cji-266185d3a962c788-shadow" },
                { name: "jeugdmaps-infrastructuur-266185d3a962c788" },
                { name: "jeugdmaps-infrastructuur-266185d3a962c788-shadow" },
                { name: "kiosk-infrastructuur-266185d3a962c788" },
                { name: "kiosk-infrastructuur-266185d3a962c788-shadow" },
                { name: "kunstenpunt-concerten-4b2e28e4c6096eb1" },
                { name: "kunstenpunt-concerten-4b2e28e4c6096eb1-shadow" },
                { name: "kunstenpunt-locaties-4b2e28e4c6096eb1" },
                { name: "kunstenpunt-locaties-4b2e28e4c6096eb1-shadow" },
                { name: "kunstenpunt-uitvoerders-4b2e28e4c6096eb1" },
                { name: "kunstenpunt-uitvoerders-4b2e28e4c6096eb1-shadow" },
                { name: "publiq-uit-activiteiten-ca17fee8e9c1fc31" },
                { name: "publiq-uit-activiteiten-ca17fee8e9c1fc31-shadow" },
                { name: "publiq-uit-locaties-ca17fee8e9c1fc31" },
                { name: "publiq-uit-locaties-ca17fee8e9c1fc31-shadow" },
                { name: "theatervoorstellingen-4b2e28e4c6096eb1" },
                { name: "theatervoorstellingen-4b2e28e4c6096eb1-shadow" }
            ],
            subDirs: []
        }
    ]
};